AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation Template for Phonebook Application. This template aims to create a phonebook application in Python and deployed as a web application with Flask on AWS Application Load Balancer with Auto Scaling Group of Elastic Compute Cloud (EC2) Instances and Relational Database Service (RDS) using AWS Cloudformation Service. Application allows users to search, add, update and delete the phonebook records and the phonebook records is kept in separate MySQL database in AWS RDS service.
Parameters:
  
Resources:
  ALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP for Application Load Balancer 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP for Flask Web Server and SSH for entering to EC2 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          SourceSecurityGroupId: !GetAtt ALBSG.GroupId
  WebServerLT:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: "String"
        InstanceInitiatedShutdownBehavior: "String"
        InstanceType: "String"
        KernelId: "String"
        KeyName: "String"
        LicenseSpecifications:
          -
        NetworkInterfaces:
          -
        RamDiskId: "String"
        SecurityGroupIds:
          -
        SecurityGroups:
          -
        TagSpecifications:
          -
        UserData: "String"
      LaunchTemplateName: "String"
      TagSpecifications:
        TagSpecifications
        

Outputs: